import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { pool, withTransaction } from "@aio/database";
const available = Boolean(process.env.DATABASE_URL);
async function fixture() { const suffix = randomUUID(); const user = await pool.query<{ id: string }>("INSERT INTO users(email_normalized) VALUES($1) RETURNING id", [`permission-${suffix}@example.test`]); const mailbox = await pool.query<{ id: string }>("INSERT INTO mailbox_accounts(user_id,provider,provider_account_id,email_address,encrypted_refresh_token,granted_scopes) VALUES($1,'gmail',$2,$3,'old-token',ARRAY['https://www.googleapis.com/auth/gmail.readonly']) RETURNING id", [user.rows[0].id, suffix, `permission-${suffix}@example.test`]); return { userId: user.rows[0].id, mailboxId: mailbox.rows[0].id }; }
async function cleanup(userId: string) { await pool.query("DELETE FROM users WHERE id=$1", [userId]); }
async function transition(mailboxId: string, attemptId: string, next: string, event: string, reason: string) { return withTransaction(async (client) => { const result = await client.query("UPDATE mailbox_permission_state SET write_capability=$3,upgrade_expires_at=NULL WHERE mailbox_account_id=$1 AND write_capability='upgrade_pending' AND upgrade_attempt_id=$2 RETURNING mailbox_account_id", [mailboxId, attemptId, next]); if (result.rowCount) await client.query("INSERT INTO audit_events(actor_type,event_type,object_type,object_id,correlation_id,metadata) VALUES('system',$1,'mailbox_account',$2,gen_random_uuid(),$3)", [event, mailboxId, JSON.stringify({ attemptId, reason })]); return result.rowCount; }); }
async function pending(mailboxId: string, attemptId: string, expires = "now()+interval '10 minutes'") { await pool.query(`INSERT INTO mailbox_permission_state(mailbox_account_id,write_capability,upgrade_attempt_id,upgrade_expires_at) VALUES($1,'upgrade_pending',$2,${expires})`, [mailboxId, attemptId]); }
test("permission attempts clean expiry, bind guarded outcomes, and preserve newer credentials", { skip: !available }, async () => { const f = await fixture(); try { const expired = randomUUID(); await pending(f.mailboxId, expired, "now()-interval '1 minute'"); const cleaned = await transition(f.mailboxId, expired, "read_only", "gmail.write_permission_expired", "expired"); assert.equal(cleaned, 1); let state = await pool.query<{ write_capability: string }>("SELECT write_capability FROM mailbox_permission_state WHERE mailbox_account_id=$1", [f.mailboxId]); assert.equal(state.rows[0].write_capability, "read_only"); const a = randomUUID(); await pool.query("UPDATE mailbox_permission_state SET write_capability='upgrade_pending',upgrade_attempt_id=$2,upgrade_expires_at=now()+interval '10 minutes' WHERE mailbox_account_id=$1", [f.mailboxId, a]); assert.equal(await transition(f.mailboxId, randomUUID(), "upgrade_failed", "x", "mismatch"), 0); await pool.query("UPDATE mailbox_permission_state SET write_capability='write_granted',upgrade_expires_at=NULL WHERE mailbox_account_id=$1 AND upgrade_attempt_id=$2", [f.mailboxId, a]); assert.equal(await transition(f.mailboxId, a, "upgrade_declined", "x", "late"), 0); const token = await pool.query<{ encrypted_refresh_token: string }>("SELECT encrypted_refresh_token FROM mailbox_accounts WHERE id=$1", [f.mailboxId]); assert.equal(token.rows[0].encrypted_refresh_token, "old-token"); } finally { await cleanup(f.userId); } });
test("permission transition audits are secret-free and duplicate callbacks are rejected", { skip: !available }, async () => { const f = await fixture(); try { const attempt = randomUUID(); await pending(f.mailboxId, attempt); assert.equal(await transition(f.mailboxId, attempt, "upgrade_declined", "gmail.write_permission_declined", "consent_denied"), 1); assert.equal(await transition(f.mailboxId, attempt, "upgrade_declined", "gmail.write_permission_declined", "duplicate"), 0); const events = await pool.query<{ event_type: string; metadata: unknown }>("SELECT event_type,metadata FROM audit_events WHERE object_id=$1", [f.mailboxId]); assert.equal(events.rows.length, 1); const serialized = JSON.stringify(events.rows[0]); for (const secret of ["state", "code", "verifier", "access_token", "refresh_token", "token response"]) assert.doesNotMatch(serialized, new RegExp(secret, "i")); } finally { await cleanup(f.userId); } });
