import { useEffect, useState } from "react";

type Command = { id: string; status: "pending" | "running" | "succeeded" | "retryable" | "failed" | "recovery_required"; draftId: string; failure_code?: string | null };
type Draft = { id: string; status: string; to: string[]; subject: string; plainText: string };
type State = "idle" | "editing" | "creating" | "loading" | "ready" | "failed" | "permission" | "reauth";
const csrf = () => document.cookie.split("; ").find((item) => item.startsWith("aio_csrf="))?.slice(9) ?? "";

export function DraftComposer({ mailboxId, onPermissionRequired }: { mailboxId: string; onPermissionRequired?: () => void }) {
  const [state, setState] = useState<State>("idle"); const [command, setCommand] = useState<Command | null>(null); const [draft, setDraft] = useState<Draft | null>(null);
  const [to, setTo] = useState(""); const [subject, setSubject] = useState(""); const [plainText, setPlainText] = useState("");
  useEffect(() => { if (!command || !["pending", "running", "retryable"].includes(command.status)) return; const timer = setTimeout(() => void fetch(`/v1/mailboxes/${mailboxId}/provider-commands/${command.id}`, { credentials: "include" }).then((response) => response.ok ? response.json() : null).then((value) => { if (!value) { setState("failed"); return; } if (value.status === "recovery_required" && value.failure_code === "write_scope_required") { setState("permission"); return; } if (value.status === "recovery_required" && value.failure_code === "reauthorization_required") { setState("reauth"); return; } setCommand((current) => current ? { ...current, status: value.status, failure_code: value.failure_code } : current); }), 800); return () => clearTimeout(timer); }, [command, mailboxId]);
  useEffect(() => { if (!command || command.status !== "succeeded") return; setState("loading"); void fetch(`/v1/mailboxes/${mailboxId}/drafts/${command.draftId}`, { credentials: "include" }).then((response) => response.ok ? response.json() : null).then((value) => { if (!value) { setState("failed"); return; } setDraft(value); setState("ready"); }); }, [command, mailboxId]);
  const create = async () => { if (state !== "editing" || command) return; setState("creating"); const response = await fetch(`/v1/mailboxes/${mailboxId}/drafts`, { method: "POST", credentials: "include", headers: { "content-type": "application/json", "x-csrf-token": csrf(), "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ to: to ? [to] : [], cc: [], bcc: [], subject, plainText, html: null }) }); const body = await response.json().catch(() => null); if (response.status === 409 && body?.code === "permission_required") { setState("permission"); return; } if (response.status === 409 && body?.code === "provider_reauthentication_required") { setState("reauth"); return; } if (!response.ok || !body?.id || !body?.draftId) { setState("failed"); return; } setCommand({ id: body.id, draftId: body.draftId, status: body.status }); };
  if (state === "idle") return <section className="draft-composer"><button className="button" type="button" onClick={() => setState("editing")}>New draft</button><p>Drafts are created in Gmail before they are shown here.</p></section>;
  if (state === "permission") return <section className="draft-composer" role="status"><p>Gmail write permission is required to create a draft.</p><button className="button" type="button" onClick={onPermissionRequired}>Enable Gmail actions</button></section>;
  if (state === "reauth") return <section className="draft-composer" role="status"><p>Reconnect Gmail before creating a draft.</p><form action="/v1/auth/google/start" method="post"><button className="button" type="submit">Reconnect Gmail</button></form></section>;
  if (state === "ready" && draft) return <section className="draft-composer" aria-label="Draft"><p role="status">Draft ready</p><p>To: {draft.to.join(", ")}</p><h2>{draft.subject || "(No subject)"}</h2><pre>{draft.plainText}</pre></section>;
  if (state === "failed" || command?.status === "failed" || command?.status === "recovery_required") return <section className="draft-composer" role="status"><p>{command?.status === "recovery_required" ? "Gmail needs verification before this draft can be shown." : "We could not create this draft."}</p><button type="button" onClick={() => { setCommand(null); setState("idle"); }}>Dismiss</button></section>;
  if (state === "editing") return <section className="draft-composer"><label>To<input value={to} onChange={(event) => setTo(event.target.value)} /></label><label>Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label>Message<textarea value={plainText} onChange={(event) => setPlainText(event.target.value)} /></label><button className="button" type="button" onClick={() => void create()}>Create draft</button></section>;
  return <section className="draft-composer" aria-live="polite"><p>{command?.status === "retryable" ? "Creating draft will retry…" : "Creating draft…"}</p></section>;
}
