import { useEffect, useState } from "react";
import { readerIframePolicy, sandboxedDocument } from "./safe-iframe.js";
import { readerFailureState, type ReaderState } from "./reader-state.js";
type Message = { id: string; from: string | null; to: string[]; subject: string | null; sentAt: string | null; attachments: Array<{ filename: string; mimeType: string; size: number | null }>; plainText: string; sanitizedHtml: string | null; renderingState: "ready" | "fallback" | "failed" };
type Thread = { id: string; messages: Message[] };
export function ThreadReader({ mailboxId, threadId }: { mailboxId: string; threadId?: string }) {
  const [state, setState] = useState<ReaderState>(threadId ? "loading" : "idle"); const [thread, setThread] = useState<Thread | null>(null); const [attempt, setAttempt] = useState(0);
  useEffect(() => { if (!threadId) { setState("idle"); setThread(null); return; } let active = true; setState("loading"); setThread(null); void fetch(`/v1/mailboxes/${mailboxId}/threads/${encodeURIComponent(threadId)}`, { credentials: "include" }).then(async (response) => { if (!active) return; if (response.ok) { setThread(await response.json() as Thread); setState("ready"); return; } const body = await response.json().catch(() => null) as { code?: string } | null; setState(readerFailureState(body?.code)); }).catch(() => active && setState("error")); return () => { active = false; }; }, [attempt, mailboxId, threadId]);
  if (state === "idle") return <div className="reader-empty"><span aria-hidden="true">◌</span><h2>Select a conversation</h2><p>Choose a thread from the list to read it.</p></div>;
  if (state === "loading") return <section className="reader-state" aria-live="polite"><div className="reader-skeleton" /><div className="reader-skeleton" /><span>Loading conversation…</span></section>;
  if (state === "deleted") return <section className="reader-state"><h2>This conversation is no longer available</h2><p>It may have been deleted in Gmail.</p></section>;
  if (state === "disconnected") return <section className="reader-state"><h2>Reconnect Gmail to read this conversation</h2><p>Your connection needs attention before we can load it.</p></section>;
  if (state === "rendering-failure") return <section className="reader-state"><h2>We could not render this conversation safely</h2><p>No unfiltered content was shown.</p><button className="button" type="button" onClick={() => setAttempt((value) => value + 1)}>Try again</button></section>;
  if (state === "error" || !thread) return <section className="reader-state"><h2>We could not load this conversation</h2><p>Gmail may be temporarily unavailable.</p><button className="button" type="button" onClick={() => setAttempt((value) => value + 1)}>Try again</button></section>;
  return <section className="thread-reader" aria-label="Conversation">{thread.messages.map((message) => <article className="message" key={message.id}><header><strong>{message.from ?? "Unknown sender"}</strong><time>{message.sentAt ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(message.sentAt)) : ""}</time><p>{message.to.length ? `To: ${message.to.join(", ")}` : ""}</p><h2>{message.subject || "(No subject)"}</h2></header>{message.attachments.length > 0 && <p className="attachment-note">{message.attachments.length} attachment{message.attachments.length === 1 ? "" : "s"} (downloads are unavailable)</p>}{message.renderingState === "failed" && <p className="render-warning">Displayed as safe plain text because rich content could not be rendered.</p>}{message.sanitizedHtml ? <iframe title={`Message from ${message.from ?? "unknown sender"}`} className="message-html" {...readerIframePolicy} srcDoc={sandboxedDocument(message.sanitizedHtml)} /> : <pre className="message-plain">{message.plainText}</pre>}</article>)}</section>;
}
