import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { pool, withTransaction } from "../index.js";
import type { ProviderCommandStatus, ProviderCommandType } from "@aio/contracts";
export class IdempotencyConflictError extends Error { constructor() { super("idempotency key conflicts with an existing request"); } }
export type Command = { id: string; mailboxAccountId: string; commandType: ProviderCommandType; status: ProviderCommandStatus; attemptCount: number; nextAttemptAt: Date; activeClaimId: string | null; leaseExpiresAt: Date | null };
const select = `id,mailbox_account_id AS "mailboxAccountId",command_type AS "commandType",status,attempt_count AS "attemptCount",next_attempt_at AS "nextAttemptAt",active_claim_id AS "activeClaimId",lease_expires_at AS "leaseExpiresAt"`;
export async function insertProviderCommand(input: { mailboxId: string; commandType: ProviderCommandType; encryptedPayload: string; fingerprint: string; idempotencyKey: string }) { return withTransaction(async (client) => { const existing = await client.query<Command & { request_fingerprint: string }>(`SELECT ${select},request_fingerprint FROM provider_commands WHERE mailbox_account_id=$1 AND idempotency_key=$2 FOR UPDATE`, [input.mailboxId,input.idempotencyKey]); if (existing.rowCount) { if (existing.rows[0].request_fingerprint !== input.fingerprint) throw new IdempotencyConflictError(); return existing.rows[0]; } const command = await client.query<Command>(`INSERT INTO provider_commands(mailbox_account_id,command_type,encrypted_payload,request_fingerprint,idempotency_key,status) VALUES($1,$2,$3,$4,$5,'pending') RETURNING ${select}`, [input.mailboxId,input.commandType,input.encryptedPayload,input.fingerprint,input.idempotencyKey]); await client.query("INSERT INTO outbox_events(aggregate_type,aggregate_id,event_type,payload) VALUES('provider_command',$1,'provider_command.requested','{}')", [command.rows[0].id]); return command.rows[0]; }); }
export async function claimCommand(commandId: string, leaseSeconds = 120) { const claimId = randomUUID(); return withTransaction(async (client) => { const result = await client.query<Command>(`UPDATE provider_commands SET status='running',active_claim_id=$2,lease_expires_at=now()+($3::text || ' seconds')::interval,attempt_count=attempt_count+1,updated_at=now() WHERE id=$1 AND status IN ('pending','retryable') AND next_attempt_at<=now() RETURNING ${select}`, [commandId,claimId,leaseSeconds]); if (!result.rowCount) return null; await client.query("INSERT INTO provider_command_attempts(command_id,claim_id,attempt_number,status) VALUES($1,$2,$3,'running')", [commandId,claimId,result.rows[0].attemptCount]); return { command: result.rows[0], claimId }; }); }
export async function completeClaim(commandId: string, claimId: string, status: "succeeded"|"failed"|"retryable"|"recovery_required", failureCode?: string) { const result = await pool.query(`UPDATE provider_commands SET status=$3,failure_code=$4,active_claim_id=NULL,lease_expires_at=NULL,completed_at=CASE WHEN $3 IN ('succeeded','failed','recovery_required') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' RETURNING id`, [commandId,claimId,status,failureCode ?? null]); return Boolean(result.rowCount); }
export async function recoverExpiredLeases() { return pool.query("UPDATE provider_commands SET status=CASE WHEN provider_result_reference IS NULL THEN 'retryable' ELSE 'recovery_required' END,active_claim_id=NULL,lease_expires_at=NULL,next_attempt_at=now()+interval '1 minute',failure_code='lease_expired',updated_at=now() WHERE status='running' AND lease_expires_at<now() RETURNING id"); }
