import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { pool, withTransaction } from "../index.js";
import type { ProviderCommandPayload, ProviderCommandStatus, ProviderCommandType } from "@aio/contracts";
import { decryptProviderCommandPayload } from "@aio/security";
export class IdempotencyConflictError extends Error { constructor() { super("idempotency key conflicts with an existing request"); } }
export class StaleCommandClaimError extends Error { constructor() { super("command claim is stale"); } }
export class InvalidCommandPayloadError extends Error { constructor() { super("command payload is invalid"); } }
export type Command = { id: string; mailboxAccountId: string; commandType: ProviderCommandType; status: ProviderCommandStatus; attemptCount: number; nextAttemptAt: Date; activeClaimId: string | null; leaseExpiresAt: Date | null; correlationId: string };
export const retryPolicy = { baseMs: 1_000, maxMs: 300_000, maxAttempts: 8 } as const;
/** Deterministic exponential backoff; handlers may add jitter later without changing the cap. */
export function retryDelayMs(attempt: number) { return Math.min(retryPolicy.maxMs, retryPolicy.baseMs * 2 ** Math.max(0, attempt - 1)); }
const select = `id,mailbox_account_id AS "mailboxAccountId",command_type AS "commandType",status,attempt_count AS "attemptCount",next_attempt_at AS "nextAttemptAt",active_claim_id AS "activeClaimId",lease_expires_at AS "leaseExpiresAt",correlation_id AS "correlationId"`;
export async function insertProviderCommand(input: { mailboxId: string; commandType: ProviderCommandType; encryptedPayload: string; fingerprint: string; idempotencyKey: string; correlationId?: string }) { return withTransaction(async (client) => { const existing = await client.query<Command & { request_fingerprint: string }>(`SELECT ${select},request_fingerprint FROM provider_commands WHERE mailbox_account_id=$1 AND idempotency_key=$2 FOR UPDATE`, [input.mailboxId,input.idempotencyKey]); if (existing.rowCount) { if (existing.rows[0].request_fingerprint !== input.fingerprint) throw new IdempotencyConflictError(); return existing.rows[0]; } const correlationId=input.correlationId ?? randomUUID(); const command = await client.query<Command>(`INSERT INTO provider_commands(mailbox_account_id,command_type,encrypted_payload,request_fingerprint,idempotency_key,status,correlation_id) VALUES($1,$2,$3,$4,$5,'pending',$6) RETURNING ${select}`, [input.mailboxId,input.commandType,input.encryptedPayload,input.fingerprint,input.idempotencyKey,correlationId]); await client.query("INSERT INTO outbox_events(aggregate_type,aggregate_id,event_type,payload,correlation_id) VALUES('provider_command',$1,'provider_command.requested','{}',$2)", [command.rows[0].id,correlationId]); return command.rows[0]; }); }
export async function claimCommand(commandId: string, leaseSeconds = 120) { const claimId = randomUUID(); return withTransaction(async (client) => { const result = await client.query<Command>(`UPDATE provider_commands SET status='running',active_claim_id=$2,lease_expires_at=now()+($3::text || ' seconds')::interval,attempt_count=attempt_count+1,updated_at=now() WHERE id=$1 AND status IN ('pending','retryable') AND next_attempt_at<=now() RETURNING ${select}`, [commandId,claimId,leaseSeconds]); if (!result.rowCount) return null; await client.query("INSERT INTO provider_command_attempts(command_id,claim_id,attempt_number,status) VALUES($1,$2,$3,'running')", [commandId,claimId,result.rows[0].attemptCount]); return { command: result.rows[0], claimId }; }); }
export type LoadedClaimedCommand = ProviderCommandPayload;
export async function loadClaimedCommand(client: PoolClient, commandId: string, claimId: string, key: string): Promise<LoadedClaimedCommand> { const row = await client.query<{ command_type: ProviderCommandType; encrypted_payload: string }>("SELECT command_type,encrypted_payload FROM provider_commands WHERE id=$1 AND status='running' AND active_claim_id=$2 AND lease_expires_at>now()",[commandId,claimId]); if(!row.rowCount) throw new StaleCommandClaimError(); try { return decryptProviderCommandPayload(row.rows[0].command_type,row.rows[0].encrypted_payload,key); } catch { throw new InvalidCommandPayloadError(); } }
export async function scheduleRetryFromClaim(client: PoolClient, commandId: string, claimId: string, failureCode: string) { const row=await client.query<{attempt_count:number}>("SELECT attempt_count FROM provider_commands WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!row.rowCount) throw new StaleCommandClaimError(); const attempts=row.rows[0].attempt_count, delay=retryDelayMs(attempts), status: "failed" | "retryable"=attempts>=retryPolicy.maxAttempts?"failed":"retryable"; const result=await client.query("UPDATE provider_commands SET status=$3,next_attempt_at=now()+($4::text || ' milliseconds')::interval,failure_code=$5,active_claim_id=NULL,lease_expires_at=NULL,completed_at=CASE WHEN $3='failed' THEN now() ELSE NULL END WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING id",[commandId,claimId,status,delay,failureCode]); if(!result.rowCount) throw new StaleCommandClaimError(); return {status,delay}; }
/** Durable uncertainty marker. It is written and committed before a non-idempotent Gmail create call. */
export async function markProviderExecutionStarted(client: PoolClient, commandId: string, claimId: string) { const result=await client.query("UPDATE provider_commands SET provider_execution_started_at=COALESCE(provider_execution_started_at,now()),updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING id",[commandId,claimId]); if(!result.rowCount) throw new StaleCommandClaimError(); }
export async function completeConfirmedMutation(client: PoolClient, commandId: string, claimId: string, projection: () => Promise<void>, providerResult: string) { const guard=await client.query<{correlation_id:string}>("SELECT correlation_id FROM provider_commands WHERE id=$1 AND status='running' AND active_claim_id=$2 AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!guard.rowCount) throw new StaleCommandClaimError(); await projection(); const done=await client.query("UPDATE provider_commands SET status='succeeded',provider_result_reference=$3,active_claim_id=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING mailbox_account_id",[commandId,claimId,providerResult]); if(!done.rowCount) throw new StaleCommandClaimError(); await client.query("INSERT INTO audit_events(actor_type,event_type,object_type,object_id,correlation_id,metadata) VALUES('system','provider_command.succeeded','provider_command',$1,$2,$3)",[commandId,guard.rows[0].correlation_id,JSON.stringify({providerResult})]); }
/** Atomically records a provider-confirmed conflict/failure and its projection change. */
export async function completeFailedMutation(client: PoolClient, commandId: string, claimId: string, failureCode: string, projection: () => Promise<void>) { const guard=await client.query<{correlation_id:string}>("SELECT correlation_id FROM provider_commands WHERE id=$1 AND status='running' AND active_claim_id=$2 AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!guard.rowCount) throw new StaleCommandClaimError(); await projection(); const done=await client.query("UPDATE provider_commands SET status='failed',failure_code=$3,active_claim_id=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING id",[commandId,claimId,failureCode]); if(!done.rowCount) throw new StaleCommandClaimError(); await client.query("INSERT INTO audit_events(actor_type,event_type,object_type,object_id,correlation_id,metadata) VALUES('system','provider_command.failed','provider_command',$1,$2,$3)",[commandId,guard.rows[0].correlation_id,JSON.stringify({ failureCode })]); }
/** Atomically preserves a draft projection in recovery_required with its uncertain command. */
export async function completeRecoveryRequiredMutation(client: PoolClient, commandId: string, claimId: string, failureCode: string, projection: () => Promise<void>) { const guard=await client.query("SELECT id FROM provider_commands WHERE id=$1 AND status='running' AND active_claim_id=$2 AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!guard.rowCount) throw new StaleCommandClaimError(); await projection(); const done=await client.query("UPDATE provider_commands SET status='recovery_required',failure_code=$3,active_claim_id=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING id",[commandId,claimId,failureCode]); if(!done.rowCount) throw new StaleCommandClaimError(); await client.query("INSERT INTO audit_events(actor_type,event_type,object_type,object_id,correlation_id,metadata) VALUES('system','provider_command.recovery_required','provider_command',$1,gen_random_uuid(),$2)",[commandId,JSON.stringify({ failureCode })]); }
export async function claimCreateDraftRecovery(commandId: string, leaseSeconds=120) { const claimId=randomUUID(); return withTransaction(async client=>{const result=await client.query<Command>(`UPDATE provider_commands SET active_claim_id=$2,lease_expires_at=now()+($3::text || ' seconds')::interval,updated_at=now() WHERE id=$1 AND command_type='create_draft' AND status='recovery_required' AND (active_claim_id IS NULL OR lease_expires_at<now()) RETURNING ${select}`,[commandId,claimId,leaseSeconds]); return result.rowCount?{command:result.rows[0],claimId}:null;}); }
export async function claimUpdateDraftRecovery(commandId: string, leaseSeconds=120) { const claimId=randomUUID(); return withTransaction(async client=>{const result=await client.query<Command>(`UPDATE provider_commands SET active_claim_id=$2,lease_expires_at=now()+($3::text || ' seconds')::interval,updated_at=now() WHERE id=$1 AND command_type='update_draft' AND status='recovery_required' AND (active_claim_id IS NULL OR lease_expires_at<now()) RETURNING ${select}`,[commandId,claimId,leaseSeconds]); return result.rowCount?{command:result.rows[0],claimId}:null;}); }
export async function claimSendDraftRecovery(commandId: string, leaseSeconds=120) { const claimId=randomUUID(); return withTransaction(async client=>{const result=await client.query<Command>(`UPDATE provider_commands SET active_claim_id=$2,lease_expires_at=now()+($3::text || ' seconds')::interval,updated_at=now() WHERE id=$1 AND command_type='send_draft' AND status='recovery_required' AND (active_claim_id IS NULL OR lease_expires_at<now()) RETURNING ${select}`,[commandId,claimId,leaseSeconds]); return result.rowCount?{command:result.rows[0],claimId}:null;}); }
export async function releaseCreateDraftRecoveryClaim(commandId:string,claimId:string,failureCode:string) { const result=await pool.query("UPDATE provider_commands SET active_claim_id=NULL,lease_expires_at=NULL,failure_code=$3,updated_at=now() WHERE id=$1 AND command_type='create_draft' AND status='recovery_required' AND active_claim_id=$2 RETURNING id",[commandId,claimId,failureCode]); return Boolean(result.rowCount); }
export async function releaseUpdateDraftRecoveryClaim(commandId:string,claimId:string,failureCode:string) { const result=await pool.query("UPDATE provider_commands SET active_claim_id=NULL,lease_expires_at=NULL,failure_code=$3,updated_at=now() WHERE id=$1 AND command_type='update_draft' AND status='recovery_required' AND active_claim_id=$2 RETURNING id",[commandId,claimId,failureCode]); return Boolean(result.rowCount); }
export async function releaseSendDraftRecoveryClaim(commandId:string,claimId:string,failureCode:string) { const result=await pool.query("UPDATE provider_commands SET active_claim_id=NULL,lease_expires_at=NULL,failure_code=$3,updated_at=now() WHERE id=$1 AND command_type='send_draft' AND status='recovery_required' AND active_claim_id=$2 RETURNING id",[commandId,claimId,failureCode]); return Boolean(result.rowCount); }
export async function completeRecoveredDraftCreation(client:PoolClient,commandId:string,claimId:string,projection:()=>Promise<void>) { const guard=await client.query("SELECT id FROM provider_commands WHERE id=$1 AND command_type='create_draft' AND status='recovery_required' AND active_claim_id=$2 AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!guard.rowCount) throw new StaleCommandClaimError(); await projection(); const done=await client.query("UPDATE provider_commands SET status='succeeded',provider_result_reference='create_draft_recovered',active_claim_id=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now(),failure_code=NULL WHERE id=$1 AND command_type='create_draft' AND status='recovery_required' AND active_claim_id=$2 AND lease_expires_at>now() RETURNING id",[commandId,claimId]); if(!done.rowCount) throw new StaleCommandClaimError(); await client.query("INSERT INTO audit_events(actor_type,event_type,object_type,object_id,correlation_id,metadata) VALUES('system','provider_command.recovered','provider_command',$1,gen_random_uuid(),$2)",[commandId,JSON.stringify({ operation:"create_draft_verification" })]); }
export async function completeRecoveredDraftSend(client:PoolClient,commandId:string,claimId:string,projection:()=>Promise<void>) { const guard=await client.query("SELECT id FROM provider_commands WHERE id=$1 AND command_type='send_draft' AND status='recovery_required' AND active_claim_id=$2 AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!guard.rowCount) throw new StaleCommandClaimError(); await projection(); const done=await client.query("UPDATE provider_commands SET status='succeeded',provider_result_reference='send_draft_recovered',active_claim_id=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now(),failure_code=NULL WHERE id=$1 AND command_type='send_draft' AND status='recovery_required' AND active_claim_id=$2 AND lease_expires_at>now() RETURNING id",[commandId,claimId]); if(!done.rowCount) throw new StaleCommandClaimError(); await client.query("INSERT INTO audit_events(actor_type,event_type,object_type,object_id,correlation_id,metadata) VALUES('system','provider_command.recovered','provider_command',$1,gen_random_uuid(),$2)",[commandId,JSON.stringify({ operation:"send_draft_verification" })]); }
export type ClaimedOutboxEvent = { id: string; aggregate_id: string; command_type: ProviderCommandType | null; correlation_id: string | null };
/** Claims command outbox rows together with immutable dispatch metadata, avoiding a command lookup per event. */
export async function claimOutboxEvents(limit=20, leaseSeconds=60, aggregateId?: string) { const claimId=randomUUID(); return withTransaction(async client=>{const rows=await client.query<ClaimedOutboxEvent>(`SELECT event.id,event.aggregate_id,command.command_type,command.correlation_id
  FROM outbox_events event
  LEFT JOIN provider_commands command ON command.id=event.aggregate_id
  WHERE event.published_at IS NULL AND (event.dispatch_lease_expires_at IS NULL OR event.dispatch_lease_expires_at<now()) AND event.event_type='provider_command.requested' AND ($2::uuid IS NULL OR event.aggregate_id=$2)
  ORDER BY event.created_at FOR UPDATE OF event SKIP LOCKED LIMIT $1`,[limit,aggregateId ?? null]); if(rows.rowCount) await client.query("UPDATE outbox_events SET dispatch_claim_id=$2,dispatch_claimed_at=now(),dispatch_lease_expires_at=now()+($3::text || ' seconds')::interval WHERE id=ANY($1::uuid[])",[rows.rows.map(x=>x.id),claimId,leaseSeconds]); return {claimId,events:rows.rows};}); }
export async function markOutboxPublished(eventId:string,claimId:string){return Boolean((await pool.query("UPDATE outbox_events SET published_at=now(),dispatch_claim_id=NULL,dispatch_lease_expires_at=NULL WHERE id=$1 AND dispatch_claim_id=$2 AND published_at IS NULL",[eventId,claimId])).rowCount);}
export async function releaseOutboxClaim(eventId:string,claimId:string){await pool.query("UPDATE outbox_events SET dispatch_claim_id=NULL,dispatch_lease_expires_at=NULL WHERE id=$1 AND dispatch_claim_id=$2 AND published_at IS NULL",[eventId,claimId]);}
export async function completeClaim(commandId: string, claimId: string, status: "succeeded"|"failed"|"retryable"|"recovery_required", failureCode?: string) { const result = await pool.query(`UPDATE provider_commands SET status=$3,failure_code=$4,active_claim_id=NULL,lease_expires_at=NULL,completed_at=CASE WHEN $3 IN ('succeeded','failed','recovery_required') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING id`, [commandId,claimId,status,failureCode ?? null]); return Boolean(result.rowCount); }
export async function scheduleRetry(commandId: string, claimId: string, failureCode: string) { const result = await pool.query(`UPDATE provider_commands SET status=CASE WHEN attempt_count >= $3 THEN 'failed' ELSE 'retryable' END,next_attempt_at=CASE WHEN attempt_count >= $3 THEN next_attempt_at ELSE now()+($4::text || ' milliseconds')::interval END,failure_code=$5,active_claim_id=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' RETURNING status`, [commandId,claimId,retryPolicy.maxAttempts,retryDelayMs(1),failureCode]); return result.rows[0]?.status ?? null; }
export async function recoverExpiredLeases() { return pool.query(`WITH recovered AS (
  UPDATE provider_commands
  SET status=CASE WHEN command_type IN ('create_draft','update_draft','send_draft') AND provider_execution_started_at IS NOT NULL THEN 'recovery_required' WHEN provider_result_reference IS NULL THEN 'retryable' ELSE 'recovery_required' END,
      active_claim_id=NULL,lease_expires_at=NULL,next_attempt_at=now()+interval '1 minute',
      failure_code=CASE WHEN command_type IN ('create_draft','update_draft','send_draft') AND provider_execution_started_at IS NOT NULL THEN 'provider_execution_uncertain' ELSE 'lease_expired' END,
      updated_at=now()
  WHERE status='running' AND lease_expires_at<now()
  RETURNING id,draft_id,command_type,provider_execution_started_at
), draft_recovered AS (
  UPDATE drafts d SET status='recovery_required',provider_checked_at=now(),updated_at=now()
  FROM recovered r
  WHERE r.command_type='send_draft' AND r.provider_execution_started_at IS NOT NULL
    AND d.id=r.draft_id AND d.last_command_id=r.id AND d.status='sending'
  RETURNING d.id
)
SELECT id FROM recovered`); }
