import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { pool, withTransaction } from "../index.js";
import type { ProviderCommandPayload, ProviderCommandStatus, ProviderCommandType } from "@aio/contracts";
import { decryptProviderCommandPayload } from "@aio/security";
export class IdempotencyConflictError extends Error { constructor() { super("idempotency key conflicts with an existing request"); } }
export class StaleCommandClaimError extends Error { constructor() { super("command claim is stale"); } }
export class InvalidCommandPayloadError extends Error { constructor() { super("command payload is invalid"); } }
export type Command = { id: string; mailboxAccountId: string; commandType: ProviderCommandType; status: ProviderCommandStatus; attemptCount: number; nextAttemptAt: Date; activeClaimId: string | null; leaseExpiresAt: Date | null };
export const retryPolicy = { baseMs: 1_000, maxMs: 300_000, maxAttempts: 8 } as const;
/** Deterministic exponential backoff; handlers may add jitter later without changing the cap. */
export function retryDelayMs(attempt: number) { return Math.min(retryPolicy.maxMs, retryPolicy.baseMs * 2 ** Math.max(0, attempt - 1)); }
const select = `id,mailbox_account_id AS "mailboxAccountId",command_type AS "commandType",status,attempt_count AS "attemptCount",next_attempt_at AS "nextAttemptAt",active_claim_id AS "activeClaimId",lease_expires_at AS "leaseExpiresAt"`;
export async function insertProviderCommand(input: { mailboxId: string; commandType: ProviderCommandType; encryptedPayload: string; fingerprint: string; idempotencyKey: string }) { return withTransaction(async (client) => { const existing = await client.query<Command & { request_fingerprint: string }>(`SELECT ${select},request_fingerprint FROM provider_commands WHERE mailbox_account_id=$1 AND idempotency_key=$2 FOR UPDATE`, [input.mailboxId,input.idempotencyKey]); if (existing.rowCount) { if (existing.rows[0].request_fingerprint !== input.fingerprint) throw new IdempotencyConflictError(); return existing.rows[0]; } const command = await client.query<Command>(`INSERT INTO provider_commands(mailbox_account_id,command_type,encrypted_payload,request_fingerprint,idempotency_key,status) VALUES($1,$2,$3,$4,$5,'pending') RETURNING ${select}`, [input.mailboxId,input.commandType,input.encryptedPayload,input.fingerprint,input.idempotencyKey]); await client.query("INSERT INTO outbox_events(aggregate_type,aggregate_id,event_type,payload) VALUES('provider_command',$1,'provider_command.requested','{}')", [command.rows[0].id]); return command.rows[0]; }); }
export async function claimCommand(commandId: string, leaseSeconds = 120) { const claimId = randomUUID(); return withTransaction(async (client) => { const result = await client.query<Command>(`UPDATE provider_commands SET status='running',active_claim_id=$2,lease_expires_at=now()+($3::text || ' seconds')::interval,attempt_count=attempt_count+1,updated_at=now() WHERE id=$1 AND status IN ('pending','retryable') AND next_attempt_at<=now() RETURNING ${select}`, [commandId,claimId,leaseSeconds]); if (!result.rowCount) return null; await client.query("INSERT INTO provider_command_attempts(command_id,claim_id,attempt_number,status) VALUES($1,$2,$3,'running')", [commandId,claimId,result.rows[0].attemptCount]); return { command: result.rows[0], claimId }; }); }
export type LoadedClaimedCommand = ProviderCommandPayload;
export async function loadClaimedCommand(client: PoolClient, commandId: string, claimId: string, key: string): Promise<LoadedClaimedCommand> { const row = await client.query<{ command_type: ProviderCommandType; encrypted_payload: string }>("SELECT command_type,encrypted_payload FROM provider_commands WHERE id=$1 AND status='running' AND active_claim_id=$2 AND lease_expires_at>now()",[commandId,claimId]); if(!row.rowCount) throw new StaleCommandClaimError(); try { return decryptProviderCommandPayload(row.rows[0].command_type,row.rows[0].encrypted_payload,key); } catch { throw new InvalidCommandPayloadError(); } }
export async function scheduleRetryFromClaim(client: PoolClient, commandId: string, claimId: string, failureCode: string) { const row=await client.query<{attempt_count:number}>("SELECT attempt_count FROM provider_commands WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!row.rowCount) throw new StaleCommandClaimError(); const attempts=row.rows[0].attempt_count, delay=retryDelayMs(attempts), status: "failed" | "retryable"=attempts>=retryPolicy.maxAttempts?"failed":"retryable"; const result=await client.query("UPDATE provider_commands SET status=$3,next_attempt_at=now()+($4::text || ' milliseconds')::interval,failure_code=$5,active_claim_id=NULL,lease_expires_at=NULL,completed_at=CASE WHEN $3='failed' THEN now() ELSE NULL END WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING id",[commandId,claimId,status,delay,failureCode]); if(!result.rowCount) throw new StaleCommandClaimError(); return {status,delay}; }
export async function completeConfirmedMutation(client: PoolClient, commandId: string, claimId: string, projection: () => Promise<void>, providerResult: string) { const guard=await client.query("SELECT id FROM provider_commands WHERE id=$1 AND status='running' AND active_claim_id=$2 AND lease_expires_at>now() FOR UPDATE",[commandId,claimId]); if(!guard.rowCount) throw new StaleCommandClaimError(); await projection(); const done=await client.query("UPDATE provider_commands SET status='succeeded',provider_result_reference=$3,active_claim_id=NULL,lease_expires_at=NULL,completed_at=now(),updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING mailbox_account_id",[commandId,claimId,providerResult]); if(!done.rowCount) throw new StaleCommandClaimError(); await client.query("INSERT INTO audit_events(actor_type,event_type,object_type,object_id,correlation_id,metadata) VALUES('system','provider_command.succeeded','provider_command',$1,gen_random_uuid(),$2)",[commandId,JSON.stringify({providerResult})]); }
export async function claimOutboxEvents(limit=20, leaseSeconds=60, aggregateId?: string) { const claimId=randomUUID(); return withTransaction(async client=>{const rows=await client.query<{id:string;aggregate_id:string}>("SELECT id,aggregate_id FROM outbox_events WHERE published_at IS NULL AND (dispatch_lease_expires_at IS NULL OR dispatch_lease_expires_at<now()) AND event_type='provider_command.requested' AND ($2::uuid IS NULL OR aggregate_id=$2) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT $1",[limit,aggregateId ?? null]); if(rows.rowCount) await client.query("UPDATE outbox_events SET dispatch_claim_id=$2,dispatch_claimed_at=now(),dispatch_lease_expires_at=now()+($3::text || ' seconds')::interval WHERE id=ANY($1::uuid[])",[rows.rows.map(x=>x.id),claimId,leaseSeconds]); return {claimId,events:rows.rows};}); }
export async function markOutboxPublished(eventId:string,claimId:string){return Boolean((await pool.query("UPDATE outbox_events SET published_at=now(),dispatch_claim_id=NULL,dispatch_lease_expires_at=NULL WHERE id=$1 AND dispatch_claim_id=$2 AND published_at IS NULL",[eventId,claimId])).rowCount);}
export async function releaseOutboxClaim(eventId:string,claimId:string){await pool.query("UPDATE outbox_events SET dispatch_claim_id=NULL,dispatch_lease_expires_at=NULL WHERE id=$1 AND dispatch_claim_id=$2 AND published_at IS NULL",[eventId,claimId]);}
export async function completeClaim(commandId: string, claimId: string, status: "succeeded"|"failed"|"retryable"|"recovery_required", failureCode?: string) { const result = await pool.query(`UPDATE provider_commands SET status=$3,failure_code=$4,active_claim_id=NULL,lease_expires_at=NULL,completed_at=CASE WHEN $3 IN ('succeeded','failed','recovery_required') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' AND lease_expires_at>now() RETURNING id`, [commandId,claimId,status,failureCode ?? null]); return Boolean(result.rowCount); }
export async function scheduleRetry(commandId: string, claimId: string, failureCode: string) { const result = await pool.query(`UPDATE provider_commands SET status=CASE WHEN attempt_count >= $3 THEN 'failed' ELSE 'retryable' END,next_attempt_at=CASE WHEN attempt_count >= $3 THEN next_attempt_at ELSE now()+($4::text || ' milliseconds')::interval END,failure_code=$5,active_claim_id=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND active_claim_id=$2 AND status='running' RETURNING status`, [commandId,claimId,retryPolicy.maxAttempts,retryDelayMs(1),failureCode]); return result.rows[0]?.status ?? null; }
export async function recoverExpiredLeases() { return pool.query("UPDATE provider_commands SET status=CASE WHEN provider_result_reference IS NULL THEN 'retryable' ELSE 'recovery_required' END,active_claim_id=NULL,lease_expires_at=NULL,next_attempt_at=now()+interval '1 minute',failure_code='lease_expired',updated_at=now() WHERE status='running' AND lease_expires_at<now() RETURNING id"); }
